[package]
name = "physx"
version = "1.0.1"
edition = "2021"

[lib]
name = "physxnative"
crate-type = ["cdylib"]

[dependencies]
physx-sys = "0.11.1"

[dev-dependencies]
regex = "1.7.3"

[build-dependencies]
csbindgen = "1.7.3"
